version: '3'

services:
  api:
    build: .
    network_mode: bridge
    ports:
      - "5000:5000"

  docs:
    image: swaggerapi/swagger-ui
    network_mode: bridge
    ports:
      - "8080:8080"
    volumes:
      - "./docs:/usr/share/nginx/html/doc"
    environment:
      API_URL: "doc/swagger.yaml"
    depends_on:
      - api
  